"""
All the Database related functions are defined here
"""

"""
Copyright (C) 2026 Yukthi Systems Private Limited

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License version 3
as published by the Free Software Foundation.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
version 3 along with this program. If not, see
<https://www.gnu.org/licenses/>.
"""


from .connections import PostgresDep, MemcachedDep, lifespan
from .clickhouse import get_mail_flow_logs, get_audit_logs, ch_health_check
from .handlers.backup_codes import replace_backup_codes_for_user, use_one_backup_code, check_backup_codes_for_user
from .quest_db import get_login_attempts, logins_per_domains, total_top_logins_per_domain, top_ip_logins_per_domain, get_server_stats, qdb_health_check
from .handlers.caution import create_new_caution_entry, get_caution_details, list_cautions_under_organization, delete_caution, update_caution_details, export_cautions_under_organization
from .handlers.department import create_new_department_entry, get_department_details, list_departments_under_organization, delete_department, update_department_details, export_departments_under_org
from .handlers.server import create_new_server_entry, get_servers, get_server_details, update_server_details, delete_server_and_related_data, update_server_active_status, quota_recalculation_and_update
from .handlers.filter_policy import create_filter_policy_entry, edit_filter_policy_entry, get_filter_policy_entries, delete_filter_policy_entry, get_filter_policy_entry_by_id, export_filter_policy_entries
from .handlers.identities import get_identity_info, create_new_identity_entry, list_identities_under_domain, delete_identity, update_identity_details, update_identity_password, fetch_full_id_info_by_admin
from .handlers.general_policy import create_general_policy_entry, edit_general_policy_entry, get_general_policy_entries, delete_general_policy_entry, get_general_policy_entry_by_id, export_general_policy_entries
from .handlers.restriction_policy import (
    get_restriction_policy_entry_by_id,
    export_restriction_policy_entries,
    delete_restriction_policy_entry,
    create_restriction_policy_entry,
    get_restriction_policy_entries,
    edit_restriction_policy_entry
)
from .handlers.migrations import (
    list_migrations_from_source_server_id,
    get_all_paginated_imap_sync_jobs,
    get_overall_migration_stats,
    do_manual_mailbox_migration,
    create_new_migration_entry,
    list_migrations_from_email,
    create_new_imap_sync_job
)
from .handlers.distribution_policy import (
    get_distribution_policy_entry_by_id,
    export_distribution_policy_entries,
    delete_distribution_policy_entry,
    create_distribution_policy_entry,
    get_distribution_policy_entries,
    edit_distribution_policy_entry
)
from .handlers.forwarding_policies import (
    get_forwarding_policy_entry_by_id,
    export_forwarding_policy_entries,
    delete_forwarding_policy_entry,
    create_forwarding_policy_entry,
    get_forwarding_policy_entries,
    edit_forwarding_policy_entry
)
from .handlers.attachment_policy import (
    export_attachment_policies_by_domain,
    get_attachment_policy_details_by_id,
    create_new_attachment_policy_entry,
    update_attachment_policy_details,
    get_attachment_policy_by_domain,
    delete_attachment_policy_by_id
)
from .handlers.disclaimer import (
    get_all_paginated_disclaimers_by_organization,
    get_disclaimer_details_by_id,
    create_new_disclaimer_entry,
    update_disclaimer_details,
    export_disclaimers_by_org,
    delete_disclaimer_by_id
)
from .handlers.totp import (
    approve_deny_client_session_for_app,
    update_sso_session_active_status,
    check_if_its_last_active_totp,
    check_if_app_session_is_valid,
    get_totp_entry_active_status,
    get_client_sessions_for_app,
    auth_app_validate_user,
    create_new_totp_entry,
    list_all_totp_entries,
    create_auth_session,
    delete_auth_session,
    delete_sso_session,
    delete_app_session,
    list_sso_sessions,
    delete_totp_entry,
    get_app_sessions,
    get_totp_secrets,
    alter_totp_entry,
    can_enable_totp
)
from .handlers.user import (
    replace_user_permissions_template,
    list_all_files_users_under_domain,
    list_all_chat_users_under_domain,
    admin_fetch_all_support_tickets,
    get_user_template_permissions,
    get_basic_user_details_by_id,
    create_user_session_in_cache,
    switch_email_client_session,
    delete_email_client_session,
    fetch_support_ticket_by_id,
    get_email_client_sessions,
    fetch_all_support_tickets,
    create_new_support_ticket,
    admin_update_ticket_info,
    delete_maintenance_entry,
    replace_user_permissions,
    update_maintenance_entry,
    get_hierarchy_users_list,
    create_maintenance_entry,
    fetch_ticket_follow_ups,
    toggle_chat_user_status,
    disable_two_factor_totp,
    toggle_file_user_status,
    add_follow_up_to_ticket,
    update_file_user_quota,
    enable_two_factor_totp,
    check_user_name_exists,
    get_basic_user_details,
    delete_support_ticket,
    get_maintenance_data,
    update_user_password,
    replace_user_details,
    set_email_verified,
    set_phone_verified,
    create_file_user,
    delete_file_user,
    delete_chat_user,
    create_chat_user,
    manage_email_2fa,
    create_new_user,
    replace_ui_info,
    manage_sms_2fa,
    is_parent_user,
    get_ui_info,
    delete_user
)
from .handlers.crm import (
    get_purchase_order_with_services,
    get_all_purchase_orders,
    export_purchase_orders,
    create_purchase_order,
    delete_purchase_order,
    update_purchase_order,
    get_service_details,
    update_service_info,
    create_service_link,
    delete_service_link,
    update_service_link,
    create_new_service,
    get_all_services,
    delete_service
)
from .handlers.mailbox import (
    check_migration_in_progress_for_mailbox,
    update_mailbox_activation_status,
    delete_mailbox_and_update_quota,
    get_all_mailboxes_under_domain,
    get_mailboxes_under_server,
    update_mailbox_lock_status,
    get_email_server_mappings,
    get_mailbox_lock_status,
    bulk_export_mailboxes,
    update_mailbox_quota,
    update_mailbox_info,
    list_only_mailboxes,
    get_mailbox_details,
    get_mailboxes_space,
    create_new_mailbox
)
from .handlers.domain import (
    check_if_any_migration_in_progress_of_domain,
    check_if_domain_has_associated_identities,
    update_domain_txt_verification_status,
    get_all_domains_under_organization,
    migrate_domain_to_new_organization,
    check_domain_organization_mapping,
    get_all_domains_by_organization,
    update_domain_activation_status,
    delete_domain_and_update_quota,
    update_domain_lock_status,
    get_domain_lock_status,
    get_domain_details,
    update_domain_info,
    get_domains_stats,
    create_new_domain
)
from .handlers.organization import (
    update_organization_activation_status,
    check_if_org_has_children_or_domains,
    get_total_users_under_organization,
    get_file_settings_for_organization,
    update_organization_identity_quota,
    get_chat_config_for_organization,
    get_api_keys_by_organization,
    create_or_update_chat_config,
    update_create_files_settings,
    edit_organization_details,
    update_organization_quota,
    get_organization_details,
    create_new_organization,
    edit_organization_name,
    get_organizations_list,
    get_org_space_metrics,
    get_api_key_details,
    delete_organization,
    update_api_key_info,
    update_chat_quota,
    delete_api_key,
    create_api_key
)
from .handlers.invoice import (
    create_new_invoice,
    check_revision_exists,
    get_latest_invoice_id,
    create_invoice_revision,
    initial_invoice_update_data,
    get_invoice_and_its_revisions,
    get_all_invoices_for_organization,
    get_all_invoices_for_all_organization
)


__version__ = "v3.5.1-phoenix-release"


__annotations__ = {
    "version": __version__,
    "PostgresDep": "PostgresSQL connection dependency for FastAPI",
    "MemcachedDep": "Memcached connection dependency for FastAPI",
    "lifespan": "Lifespan context manager for FastAPI to manage database connections",
    "get_organization_details": "Function to fetch organization details from the database",
    "create_new_user": "Function to create a new user in the database",
    "get_basic_user_details": "Function to get basic user details from the database",
    "set_phone_verified": "Function to set a user's phone number as verified in the database",
    "manage_sms_2fa": "Function to manage SMS-based two-factor authentication for a user",
    "get_email_client_sessions": "Function to get email client sessions for a user",
    "create_user_session_in_cache": "Function to create a user session in the cache",
    "check_user_name_exists": "Function to check if a user name already exists in the database",
    "delete_user": "Function to delete a user from the database",
    "get_user_template_permissions": "Function to get user template permissions from the database",
    "is_parent_user": "Function to check if a user is a parent user in the organization hierarchy",
    "get_hierarchy_users_list": "Function to get a list of users in the organization hierarchy",
    "update_user_password": "Function to update a user's password in the database",
    "replace_user_permissions_template": "Function to replace user permissions template in the database",
    "replace_user_permissions": "Function to replace user permissions in the database",
    "replace_user_details": "Function to replace user details in the database",
    "create_new_mailbox": "Function to create a new mailbox in the database",
    "delete_app_session": "Function to delete an application session for a user",
    "get_all_invoices_for_all_organization": "Function to get all invoices across all organizations with pagination",
    "get_filter_policy_entry_by_id": "Function to get an filter policy entry by its ID",
    "get_mailbox_details": "Function to get mailbox details from the database",
    "get_all_mailboxes_under_domain": "Function to get all mailboxes under a specific domain",
    "check_backup_codes_for_user": "Function to check if backup codes are generated for a user",
    "get_domain_details": "Function to get domain details from the database",
    "get_organizations_list": "Function to get a list of organizations from the database",
    "create_new_organization": "Function to create a new organization in the database",
    "create_new_domain": "Function to create a new domain in the database",
    "get_all_domains_by_organization": "Function to get all domains by organization from the database",
    "set_email_verified": "Function to set a user's email as verified in the database",
    "create_new_server_entry": "Function to create a new server entry in the database",
    "get_servers": "Function to get a list of servers from the database",
    "get_server_details": "Function to get details of a specific server from the database",
    "update_server_details": "Function to update details of a specific server in the database",
    "delete_server_and_related_data": "Function to delete a server and all related data from the database",
    "create_new_disclaimer_entry": "Function to create a new disclaimer entry in the database",
    "get_disclaimer_details_by_id": "Function to get details of a specific disclaimer by ID",
    "update_disclaimer_details": "Function to update details of a specific disclaimer in the database",
    "delete_disclaimer_by_id": "Function to delete a specific disclaimer by ID from the database",
    "get_all_paginated_disclaimers_by_organization": "Function to get all disclaimers for a specific organization with pagination",
    "create_new_department_entry": "Function to create a new department entry in the database",
    "get_department_details": "Function to get details of a specific department from the database",
    "list_departments_under_organization": "Function to list all departments under an organization with pagination",
    "get_total_users_under_organization": "Function to get the total number of users under a specific organization",
    "delete_department": "Function to delete a department from the database",
    "update_department_details": "Function to update details of a specific department in the database",
    "create_new_caution_entry": "Function to create a new caution message entry in the database",
    "get_caution_details": "Function to get details of a specific caution message from the database",
    "list_cautions_under_organization": "Function to list all caution messages under an organization",
    "delete_caution": "Function to delete a specific caution message from the database",
    "update_caution_details": "Function to update details of a specific caution message in the database",
    "get_purchase_order_with_services": "Function to get purchase order details along with associated services",
    "get_all_purchase_orders": "Function to get all purchase orders from the database",
    "create_purchase_order": "Function to create a new purchase order in the database",
    "manage_email_2fa": "Function to enable or disable email-based two-factor authentication for a user",
    "delete_purchase_order": "Function to delete a specific purchase order from the database",
    "update_purchase_order": "Function to update details of a specific purchase order in the database",
    "get_service_details": "Function to get details of a specific service from the database",
    "update_service_info": "Function to update information of a specific service in the database",
    "replace_backup_codes_for_user": "Function to replace all backup codes for a user with new codes",
    "use_one_backup_code": "Function to use one backup code for a user",
    "create_service_link": "Function to create a new service link in the database",
    "delete_service_link": "Function to delete a specific service link from the database",
    "get_basic_user_details_by_id": "Function to get basic user details by user ID from the database",
    "update_service_link": "Function to update details of a specific service link in the database",
    "create_new_service": "Function to create a new service in the database",
    "get_all_services": "Function to get a list of all services from the database",
    "delete_service": "Function to delete a specific service from the database",
    "enable_two_factor_totp": "Function to enable Two Factor Authentication using TOTP for a user",
    "disable_two_factor_totp": "Function to disable Two Factor Authentication using TOTP for a user",
    "create_new_totp_entry": "Function to create a new TOTP entry for a user",
    "get_totp_secrets": "Function to get all TOTP secrets for a user",
    "delete_totp_entry": "Function to delete a TOTP entry by its ID",
    "update_domain_lock_status": "Function to update the lock status of a domain",
    "can_enable_totp": "Function to check if TOTP can be enabled for a user",
    "alter_totp_entry": "Function to alter an existing TOTP entry for a user",
    "check_if_its_last_active_totp": "Function to check if a TOTP entry is the last active one for a user",
    "list_all_totp_entries": "Function to list all TOTP entries for a user",
    "get_totp_entry_active_status": "Function to get the active status of a TOTP entry",
    "create_filter_policy_entry": "Function to create a new black or white list entry for a domain",
    "edit_filter_policy_entry": "Function to edit an existing black or white list entry for a domain",
    "get_filter_policy_entries": "Function to get all filter Policy list entries for a domain",
    "delete_filter_policy_entry": "Function to delete a specific black or white list entry for a domain",
    "create_general_policy_entry": "Function to create a new general policy entry for a domain",
    "edit_general_policy_entry": "Function to edit an existing general policy entry for a domain",
    "get_general_policy_entries": "Function to get all general policy entries for a domain",
    "delete_general_policy_entry": "Function to delete a specific general policy entry for a domain",
    "get_general_policy_entry_by_id": "Function to get a specific general policy entry for a domain by its ID",
    "get_audit_logs": "Function to get audit logs from the ClickHouse database",
    "get_mail_flow_logs": "Function to get mail flow logs from the ClickHouse database",
    "update_mailbox_info": "Function to update mailbox information in the database",
    "update_mailbox_activation_status": "Function to update the activation status of a mailbox",
    "update_mailbox_quota": "Function to update the quota of a mailbox",
    "delete_mailbox_and_update_quota": "Function to delete a mailbox and update its quota in the database",
    "update_domain_info": "Function to update domain information in the database",
    "update_domain_activation_status": "Function to update the activation status of a domain",
    "update_domain_quota": "Function to update the quota of a domain",
    "delete_domain_and_update_quota": "Function to delete a domain and update its quota in the database",
    "edit_organization_details": "Function to edit organization details in the database",
    "update_organization_activation_status": "Function to update the activation status of an organization",
    "update_organization_quota": "Function to update the quota of an organization",
    "delete_organization": "Function to delete an organization from the database",
    "check_domain_organization_mapping": "Function to check if a domain is mapped to an organization",
    "get_login_attempts": "Function to get login attempts from the quest database within a specified date range",
    "get_org_space_metrics": "Function to get organization space metrics from the database",
    "get_mailboxes_space": "Function to get mailbox space metrics for domains under an organization",
    "logins_per_domains": "Function to fetch login attempts per domain",
    "total_top_logins_per_domain": "Function to fetch total top logins per domain",
    "top_ip_logins_per_domain": "Function to fetch top IP logins per domain",
    "bulk_export_mailboxes": "Function to bulk export mailboxes for a specific organization",
    "migrate_domain_to_new_organization": "Function to migrate a domain to a new organization, including associated data and space reallocation",
    "get_mailboxes_under_server": "Function to get all mailboxes under a specific server",
    "create_new_migration_entry": "Function to create a new migration entry in the database",
    "list_migrations_from_source_server_id": "Function to list all migrations from a specific source server with pagination",
    "update_mailbox_lock_status": "Function to update the lock status of a mailbox",
    "check_migration_in_progress_for_mailbox": "Function to check if a migration is in progress for a specific mailbox",
    "get_mailbox_lock_status": "Function to get the lock status of a mailbox",
    "get_domain_lock_status": "Function to get the lock status of a domain",
    "check_if_any_migration_in_progress_of_domain": "Function to check if any migration is in progress for a specific domain",
    "list_migrations_from_email": "Function to list all migrations associated with a specific email address",
    "get_server_stats": "Function to fetch server metrics for a specific server within a date range",
    "get_overall_migration_stats": "Function to get overall migration statistics, including counts of completed, in-progress, and failed migrations",
    "ch_health_check": "Function to check the health status of the ClickHouse database",
    "qdb_health_check": "Function to check the health status of the QuestDB database",
    "get_invoice_and_its_revisions": "Function to get an invoice and its revisions by invoice ID",
    "get_all_invoices_for_organization": "Function to get all invoices for a specific organization with pagination",
    "create_new_invoice": "Function to create a new invoice in the database",
    "delete_email_client_session": "Function to delete an email client session",
    "create_invoice_revision": "Function to create a new invoice revision in the database",
    "get_latest_invoice_id": "Function to get the latest invoice ID for a specific organization",
    "check_revision_exists": "Function to check if a revision exists for a specific invoice ID",
    "initial_invoice_update_data": "Function to get initial data for updating an invoice, including organization ID, invoice date, and due date",
    "replace_ui_info": "Function to replace UI-related information for a user in the database",
    "get_ui_info": "Function to get UI-related information for a user from the database",
    "switch_email_client_session": "Function to switch the email client session for a user",
    "create_auth_session": "Function to create a new authentication session for a user",
    "delete_auth_session": "Function to delete an authentication session for a user",
    "approve_deny_client_session_for_app": "Function to approve or deny a client session for the Auth App",
    "check_if_app_session_is_valid": "Function to check if an Auth App session is valid",
    "get_client_sessions_for_app": "Function to get all client sessions for the Auth App",
    "auth_app_validate_user": "Function to validate a user's phone number and email for the Auth App",
    "export_purchase_orders": "Function to export purchase orders for a specific organization",
    "export_cautions_under_organization": "Function to export caution messages for a specific organization",
    "export_disclaimers_by_org": "Function to export disclaimers for a specific organization with pagination support",
    "export_departments_under_org": "Function to export departments for a specific organization with pagination support",
    "export_filter_policy_entries": "Function to export filter policy entries for a specific organization with pagination support",
    "export_general_policy_entries": "Function to export general policy entries for a specific organization with pagination support",
    "get_maintenance_data": "Function to get maintenance data from the database",
    "get_app_sessions": "Function to get all application sessions for a user",
    "edit_organization_name": "Function to edit the name of an organization in the database",
    "export_attachment_policies_by_domain": "Function to export attachment policies for a specific domain",
    "get_attachment_policy_details_by_id": "Function to get details of a specific attachment policy by ID",
    "create_new_attachment_policy_entry": "Function to create a new attachment policy entry in the database",
    "update_attachment_policy_details": "Function to update details of a specific attachment policy in the database",
    "get_attachment_policy_by_domain": "Function to get attachment policies for a specific domain",
    "delete_attachment_policy_by_id": "Function to delete a specific attachment policy by ID from the database",
    "get_email_server_mappings": "Function to get email server mappings from the database",
    "delete_maintenance_entry": "Function to delete a maintenance entry from the database",
    "update_maintenance_entry": "Function to update a maintenance entry in the database",
    "create_maintenance_entry": "Function to create a new maintenance entry in the database",
    "list_only_mailboxes": "Function to list only mailboxes for a specific organization with pagination support",
    "create_new_support_ticket": "Function to create a new support ticket in the database",
    "add_follow_up_to_ticket": "Function to add a follow-up message to an existing support ticket in the database",
    "fetch_all_support_tickets": "Function to fetch all support tickets for an organization with pagination and search query support",
    "fetch_ticket_follow_ups": "Function to fetch all follow-ups for a support ticket with pagination",
    "admin_fetch_all_support_tickets": "Function to fetch all support tickets across organizations with pagination and search query support",
    "admin_update_ticket_info": "Function to update support ticket information such as status and assigned user in the database",
    "delete_support_ticket": "Function to delete a support ticket and its follow-ups from the database",
    "update_server_active_status": "Function to update the active status of a MailBox Server in the database",
    "fetch_support_ticket_by_id": "Function to fetch a specific support ticket by its ID from the database",
    "get_api_keys_by_organization": "Function to get all API keys for a specific organization",
    "get_api_key_details": "Function to get details of a specific API key by its ID",
    "delete_api_key": "Function to delete a specific API key by its ID",
    "update_api_key_info": "Function to update information of a specific API key in the database",
    "create_api_key": "Function to create a new API key for a specific organization in the database",
    "get_restriction_policy_entry_by_id": "Function to get a specific restriction policy entry by its ID",
    "export_restriction_policy_entries": "Function to export restriction policy entries for a specific organization with pagination support",
    "delete_restriction_policy_entry": "Function to delete a specific restriction policy entry by its ID",
    "create_restriction_policy_entry": "Function to create a new restriction policy entry in the database",
    "get_restriction_policy_entries": "Function to get restriction policy entries for a specific organization with pagination support",
    "edit_restriction_policy_entry": "Function to edit a specific restriction policy entry in the database",
    "get_distribution_policy_entry_by_id": "Function to get a specific distribution policy entry by its ID",
    "export_distribution_policy_entries": "Function to export distribution policy entries for a specific organization with pagination support",
    "delete_distribution_policy_entry": "Function to delete a specific distribution policy entry by its ID",
    "create_distribution_policy_entry": "Function to create a new distribution policy entry in the database",
    "get_distribution_policy_entries": "Function to get distribution policy entries for a specific organization with pagination support",
    "edit_distribution_policy_entry": "Function to edit a specific distribution policy entry in the database",
    "get_forwarding_policy_entry_by_id": "Function to get a specific forwarding policy entry by its ID",
    "export_forwarding_policy_entries": "Function to export forwarding policy entries for a specific organization with pagination support",
    "delete_forwarding_policy_entry": "Function to delete a specific forwarding policy entry by its ID",
    "create_forwarding_policy_entry": "Function to create a new forwarding policy entry in the database",
    "get_forwarding_policy_entries": "Function to get forwarding policy entries for a specific organization with pagination support",
    "edit_forwarding_policy_entry": "Function to edit a specific forwarding policy entry in the database",
    "do_manual_mailbox_migration": "Function to perform manual migration of a mailbox from one server to another",
    "quota_recalculation_and_update": "Function to recalculate and update quota for organizations, domains, and mailboxes",
    "create_new_imap_sync_job": "Function to create a new IMAP synchronization job in the database",
    "get_all_paginated_imap_sync_jobs": "Function to get all IMAP synchronization jobs with pagination support",
    "create_or_update_chat_config": "Function to create or update chat configuration for an organization in the database",
    "update_chat_quota": "Function to update chat quota for an organization in the database",
    "get_chat_config_for_organization": "Function to get chat configuration for a specific organization from the database",
    "get_all_domains_under_organization": "Function to get all domains under a specific organization from the database",
    "get_identity_info": "Function to get identity information for a user from the database",
    "update_organization_identity_quota": "Function to update the identity quota for an organization in the database",
    "create_new_identity_entry": "Function to create a new identity entry in the database",
    "list_identities_under_domain": "Function to list all identities under a specific domain in the database, same for the export also",
    "delete_identity": "Function to delete a specific identity from the database",
    "update_identity_details": "Function to update details of a specific identity in the database",
    "update_identity_password": "Function to update the password of a specific identity in the database",
    "list_sso_sessions": "Function to list all SSO sessions for a user from the database",
    "delete_sso_session": "Function to delete a specific SSO session for a user from the database",
    "list_all_chat_users_under_domain": "Function to list all chat users under a specific domain from the database",
    "toggle_chat_user_status": "Function to toggle the status of a chat user in the database",
    "delete_chat_user": "Function to delete a specific chat user from the database",
    "create_chat_user": "Function to create a new chat user in the database",
    "get_domains_stats": "Function to get total domains, active domains, and inactive domains count for a specific organization from the database",
    "fetch_full_id_info_by_admin": "Function to fetch full identity information by an admin for a specific identity ID from the database",
    "update_domain_txt_verification_status": "Function to update the TXT verification status of a domain in the database",
    "check_if_org_has_children_or_domains": "Function to check if an organization has any child organizations or associated domains before deletion",
    "check_if_domain_has_associated_identities": "Function to check if a domain has any associated identities before deletion",
    "update_sso_session_active_status": "Function to update the active status of an SSO session for a user in the database",
    "get_file_settings_for_organization": "Function to get file settings for a specific organization from the database",
    "update_create_files_settings": "Function to update or create file settings for a specific organization in the database",
    "list_all_files_users_under_domain": "Function to list all file users under a specific domain from the database",
    "toggle_file_user_status": "Function to toggle the status of a file user in the database",
    "delete_file_user": "Function to delete a specific file user from the database",
    "create_file_user": "Function to create a new file user in the database",
    "update_file_user_quota": "Function to update the quota of a file user in the database"
}


__all__ = [
    "PostgresDep",
    "MemcachedDep",
    "lifespan",
    "get_organization_details",
    "create_new_user",
    "get_basic_user_details",
    "create_user_session_in_cache",
    "check_user_name_exists",
    "delete_user",
    "is_parent_user",
    "get_hierarchy_users_list",
    "update_user_password",
    "replace_user_permissions_template",
    "replace_user_permissions",
    "replace_user_details",
    "set_email_verified",
    "create_new_mailbox",
    "get_mailbox_details",
    "get_all_mailboxes_under_domain",
    "get_domain_details",
    "get_basic_user_details_by_id",
    "get_organizations_list",
    "create_new_organization",
    "create_new_domain",
    "get_all_domains_by_organization",
    "create_new_server_entry",
    "check_backup_codes_for_user",
    "get_servers",
    "get_server_details",
    "update_server_details",
    "delete_server_and_related_data",
    "create_new_disclaimer_entry",
    "get_disclaimer_details_by_id",
    "update_disclaimer_details",
    "delete_disclaimer_by_id",
    "get_all_paginated_disclaimers_by_organization",
    "create_new_department_entry",
    "get_department_details",
    "set_phone_verified",
    "manage_sms_2fa",
    "list_departments_under_organization",
    "delete_department",
    "update_department_details",
    "create_new_caution_entry",
    "get_caution_details",
    "list_cautions_under_organization",
    "delete_caution",
    "update_caution_details",
    "get_purchase_order_with_services",
    "get_all_purchase_orders",
    "create_purchase_order",
    "delete_purchase_order",
    "update_purchase_order",
    "get_service_details",
    "update_service_info",
    "create_service_link",
    "delete_service_link",
    "manage_email_2fa",
    "update_service_link",
    "create_new_service",
    "get_all_services",
    "delete_service",
    "enable_two_factor_totp",
    "disable_two_factor_totp",
    "create_new_totp_entry",
    "get_totp_secrets",
    "delete_totp_entry",
    "can_enable_totp",
    "alter_totp_entry",
    "check_if_its_last_active_totp",
    "get_user_template_permissions",
    "list_all_totp_entries",
    "get_totp_entry_active_status",
    "replace_backup_codes_for_user",
    "use_one_backup_code",
    "create_filter_policy_entry",
    "edit_filter_policy_entry",
    "get_filter_policy_entries",
    "delete_filter_policy_entry",
    "get_filter_policy_entry_by_id",
    "create_general_policy_entry",
    "edit_general_policy_entry",
    "get_general_policy_entries",
    "delete_general_policy_entry",
    "get_general_policy_entry_by_id",
    "get_audit_logs",
    "get_mail_flow_logs",
    "update_mailbox_info",
    "update_mailbox_activation_status",
    "update_mailbox_quota",
    "delete_mailbox_and_update_quota",
    "update_domain_info",
    "update_domain_activation_status",
    "delete_domain_and_update_quota",
    "edit_organization_details",
    "update_organization_activation_status",
    "update_organization_quota",
    "delete_organization",
    "check_domain_organization_mapping",
    "get_login_attempts",
    "get_org_space_metrics",
    "get_mailboxes_space",
    "get_total_users_under_organization",
    "logins_per_domains",
    "total_top_logins_per_domain",
    "top_ip_logins_per_domain",
    "bulk_export_mailboxes",
    "migrate_domain_to_new_organization",
    "get_mailboxes_under_server",
    "create_new_migration_entry",
    "list_migrations_from_source_server_id",
    "update_mailbox_lock_status",
    "update_domain_lock_status",
    "check_migration_in_progress_for_mailbox",
    "get_mailbox_lock_status",
    "get_domain_lock_status",
    "check_if_any_migration_in_progress_of_domain",
    "list_migrations_from_email",
    "get_server_stats",
    "get_overall_migration_stats",
    "ch_health_check",
    "qdb_health_check",
    "get_invoice_and_its_revisions",
    "get_all_invoices_for_organization",
    "create_new_invoice",
    "create_invoice_revision",
    "get_latest_invoice_id",
    "check_revision_exists",
    "get_email_client_sessions",
    "initial_invoice_update_data",
    "replace_ui_info",
    "get_ui_info",
    "switch_email_client_session",
    "delete_email_client_session",
    "create_auth_session",
    "delete_auth_session",
    "approve_deny_client_session_for_app",
    "check_if_app_session_is_valid",
    "get_client_sessions_for_app",
    "auth_app_validate_user",
    "export_purchase_orders",
    "export_cautions_under_organization",
    "export_disclaimers_by_org",
    "export_departments_under_org",
    "export_filter_policy_entries",
    "export_general_policy_entries",
    "get_maintenance_data",
    "get_app_sessions",
    "edit_organization_name",
    "export_attachment_policies_by_domain",
    "get_attachment_policy_details_by_id",
    "create_new_attachment_policy_entry",
    "update_attachment_policy_details",
    "get_attachment_policy_by_domain",
    "delete_attachment_policy_by_id",
    "get_email_server_mappings",
    "delete_maintenance_entry",
    "update_maintenance_entry",
    "create_maintenance_entry",
    "list_only_mailboxes",
    "create_new_support_ticket",
    "add_follow_up_to_ticket",
    "fetch_all_support_tickets",
    "fetch_ticket_follow_ups",
    "admin_fetch_all_support_tickets",
    "admin_update_ticket_info",
    "delete_support_ticket",
    "update_server_active_status",
    "fetch_support_ticket_by_id",
    "get_api_keys_by_organization",
    "get_api_key_details",
    "delete_api_key",
    "update_api_key_info",
    "create_api_key",
    "get_restriction_policy_entry_by_id",
    "export_restriction_policy_entries",
    "delete_restriction_policy_entry",
    "create_restriction_policy_entry",
    "get_restriction_policy_entries",
    "edit_restriction_policy_entry",
    "get_distribution_policy_entry_by_id",
    "export_distribution_policy_entries",
    "delete_distribution_policy_entry",
    "create_distribution_policy_entry",
    "get_distribution_policy_entries",
    "edit_distribution_policy_entry",
    "get_forwarding_policy_entry_by_id",
    "export_forwarding_policy_entries",
    "delete_forwarding_policy_entry",
    "create_forwarding_policy_entry",
    "get_forwarding_policy_entries",
    "edit_forwarding_policy_entry",
    "get_all_invoices_for_all_organization",
    "delete_app_session",
    "do_manual_mailbox_migration",
    "quota_recalculation_and_update",
    "create_new_imap_sync_job",
    "get_all_paginated_imap_sync_jobs",
    "create_or_update_chat_config",
    "update_chat_quota",
    "get_chat_config_for_organization",
    "get_all_domains_under_organization",
    "get_identity_info",
    "update_organization_identity_quota",
    "create_new_identity_entry",
    "list_identities_under_domain",
    "delete_identity",
    "update_identity_details",
    "update_identity_password",
    "delete_sso_session",
    "list_sso_sessions",
    "list_all_chat_users_under_domain",
    "toggle_chat_user_status",
    "delete_chat_user",
    "create_chat_user",
    "get_domains_stats",
    "fetch_full_id_info_by_admin",
    "update_domain_txt_verification_status",
    "check_if_org_has_children_or_domains",
    "check_if_domain_has_associated_identities",
    "update_sso_session_active_status",
    "get_file_settings_for_organization",
    "update_create_files_settings",
    "list_all_files_users_under_domain",
    "toggle_file_user_status",
    "delete_file_user",
    "update_file_user_quota",
    "create_file_user"
]
